services:
  app:
    container_name: knowledge-base-system
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8000:3000
    volumes:
      - .:/app
      - /app/node_modules
